{% set name = "plpygis" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plpygis-{{ version }}.tar.gz
  sha256: 30a119b3d5a60e285a7a66ee95b65a5efcc0d569b2d02d3183e736bbad7f748b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - plpygis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bosth/plpygis
  summary: PostGIS Python tools
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tylere
