{% set name = "plpygis" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plpygis-{{ version }}.tar.gz
  sha256: f63baf26f38b2d674a37402b4f69a4a6d1e896416016f4b1714f96950c03ed86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - plpygis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bosth/plpygis
  summary: PostGIS Python tools
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tylere
